# read alignment + preprocessing ------------------------------------------------------------------

FASTQ_SCREEN_CONFIG: config/fastq_screen.conf

GTF:  # /home/groups/MaxsonLab/indices/mm10/STAR_index/Mus_musculus.GRCm39.104.gtf
  # /home/groups/MaxsonLab/indices/GRch38/STAR_index/Homo_sapiens.GRCh38.104.gtf

STAR:
  # /home/groups/MaxsonLab/indices/mm10/STAR_index
  # /home/groups/MaxsonLab/indices/GRch38/STAR_index

FASTA:
  # /home/groups/MaxsonLab/indices/mm10/STAR_index/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa
  # /home/groups/MaxsonLab/indices/GRch38/bowtie2/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta

ASSEMBLY:
  # mm10
  # hg38

# counts + feature filter -------------------------------------------------------------------------

PROJECT_ID: "project_id"

# types of features to retain. Can be a string or list of strings.
# recommended options: ["protein_coding", "lncRNA", "miRNA", "snoRNA", "snRNA", "Mt_tRNA"]
BIOTYPES: "protein_coding"

ANNOTATION: "config/mouse-annotation.txt.gz"
# config/human-annotation.txt.gz

# type of annotation style in the STAR index.
# Genes is when annotation style is gene name.
ANNOTATION_STYLE: "Genes" # ["Genes", "UCSC", "ENSEMBL_ID", "REFSEQ", "NCBI"]

# differential analysis ---------------------------------------------------------------------------

PADJ: 0.05
DESEQ2_CONFIG: "config/metadata.txt"
CONTRASTS: "config/contrasts.txt"
# a REQUIRED 2-column table (tab-separated format, no header) containing pairwise combinations to assess.
# the order of conditions matter (column1-vs-column2) to facilitate biological interpretation.

# CONTRASTS example:
# TREATMENT_1 DMSO
# TREATMENT_2 DMSO

GROUPS: "config/groups.txt"
# an OPTIONAL 1-column table containing all the conditions used for group DESeq2 analysis.
# the order of conditions affect the plot order in the output heatmap.
# by default, use all the conditions in the metadata.

# GROUPS example:
# TREATMENT_1
# TREATMENT_2
# DMSO

MERGE_REPLICATES: True # [True, False]

REPLICATES: "config/replicates.yaml"
# an optional YAML file that lists biological replicates. Ignored if MERGE_REPLICATES is False. Example below:
# DMSO:
#   DMSO_1
#   DMSO_2
#   DMSO_3
# TREATMENT:
#   TREATMENT_1
#   TREATMENT_2
#   TREATMENT_3
# where DMSO/TREATMENT is a custom name, and {DMSO|TREATMENT}_1 are actual replicate names.
# MERGE_REPLICATES must be True and REPLICATES be populated to merge replicates. Reps will NOT be inferred.

MERGE_METHOD: 'median' # ['mean', 'median']
# specify how should replicates be merged. Unused if MERGE_REPLICATES = False.

# List covariates in your analysis in the form of an R formula. Currently, only Condition is supported.
MODEL: "~Condition"
