# pipeline config ---------------------------------------------------------------------------------

FASTQ_SCREEN_CONFIG: config/fastq_screen.conf
DESEQ2_CONFIG: config/metadata.txt

# read alignment + preprocessing ------------------------------------------------------------------

GTF: /home/groups/MaxsonLab/indices/mm10/STAR_index/Mus_musculus.GRCm39.104.gtf
  # /home/groups/MaxsonLab/indices/mm10/STAR_index/Mus_musculus.GRCm39.104.gtf
  # /home/groups/MaxsonLab/indices/GRch38/STAR_index/Homo_sapiens.GRCh38.104.gtf
STAR: /home/groups/MaxsonLab/indices/mm10/STAR_index
  # /home/groups/MaxsonLab/indices/mm10/STAR_index
  # /home/groups/MaxsonLab/indices/GRch38/STAR_index
FASTA: /home/groups/MaxsonLab/indices/mm10/STAR_index/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa
  # /home/groups/MaxsonLab/indices/mm10/STAR_index/Mus_musculus.GRCm39.dna_sm.primary_assembly.fa
  # /home/groups/MaxsonLab/indices/GRch38/bowtie2/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta
ASSEMBLY: mm10
  # mm10
  # hg38

PROJECT_ID: "project_id"

# differential analysis ---------------------------------------------------------------------------

# keep results with pval less than <padj_cutoff>
padj_cutoff: 0.05

diffexp:
  contrasts:
    # should be in format:
    # target-vs-baseline
  groups:
    # should be in format:
    # - condition1
    # - condition2
    # - ...
    # - baseline
